/* This is a template file generated by command */
/* orbit-idl-2 --skeleton-impl echo.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

#include "echo.h"

/*** App-specific servant structures ***/

#if !defined(_typedef_impl_POA_EchoApp_Echo_)
#define _typedef_impl_POA_EchoApp_Echo_ 1
typedef struct {
POA_EchoApp_Echo servant;
PortableServer_POA poa;
   /* ------ add private attributes here ------ */
   /* ------ ---------- end ------------ ------ */
} impl_POA_EchoApp_Echo;
#endif


/*** Implementation stub prototypes ***/

#if !defined(_decl_impl_EchoApp_Echo__destroy_)
#define _decl_impl_EchoApp_Echo__destroy_ 1
static void impl_EchoApp_Echo__destroy(impl_POA_EchoApp_Echo *servant,
CORBA_Environment *ev);
#endif

#if !defined(_decl_impl_EchoApp_Echo_echoString_)
#define _decl_impl_EchoApp_Echo_echoString_ 1
static void
impl_EchoApp_Echo_echoString(impl_POA_EchoApp_Echo *servant,
const CORBA_char * input,
CORBA_Environment *ev);
#endif


/*** epv structures ***/

#if !defined(_impl_EchoApp_Echo_base_epv_)
#define _impl_EchoApp_Echo_base_epv_ 1
static PortableServer_ServantBase__epv impl_EchoApp_Echo_base_epv = {
NULL,             /* _private data */
(gpointer) & impl_EchoApp_Echo__destroy, /* finalize routine */
NULL,             /* default_POA routine */
};
#endif

#if !defined(_impl_EchoApp_Echo_epv_)
#define _impl_EchoApp_Echo_epv_ 1
static POA_EchoApp_Echo__epv impl_EchoApp_Echo_epv = {
NULL, /* _private */
(gpointer)&impl_EchoApp_Echo_echoString,
};
#endif


/*** vepv structures ***/

#if !defined(_impl_EchoApp_Echo_vepv_)
#define _impl_EchoApp_Echo_vepv_ 1
static POA_EchoApp_Echo__vepv impl_EchoApp_Echo_vepv = {
&impl_EchoApp_Echo_base_epv,
&impl_EchoApp_Echo_epv,
};
#endif


/*** Stub implementations ***/

#if !defined(_impl_EchoApp_Echo__create_)
#define _impl_EchoApp_Echo__create_ 1
static EchoApp_Echo impl_EchoApp_Echo__create(PortableServer_POA poa, CORBA_Environment *ev)
{
EchoApp_Echo retval;
impl_POA_EchoApp_Echo *newservant;
PortableServer_ObjectId *objid;

newservant = g_new0(impl_POA_EchoApp_Echo, 1);
newservant->servant.vepv = &impl_EchoApp_Echo_vepv;
newservant->poa = (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object)poa, ev);
POA_EchoApp_Echo__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

objid = PortableServer_POA_activate_object(poa, newservant, ev);
CORBA_free(objid);
retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

return retval;
}
#endif

#if !defined(_impl_EchoApp_Echo__destroy_)
#define _impl_EchoApp_Echo__destroy_ 1
static void
impl_EchoApp_Echo__destroy(impl_POA_EchoApp_Echo *servant, CORBA_Environment *ev)
{
    CORBA_Object_release ((CORBA_Object) servant->poa, ev);

    /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

POA_EchoApp_Echo__fini((PortableServer_Servant)servant, ev);

g_free (servant);
}
#endif

#if !defined(_impl_EchoApp_Echo_echoString_)
#define _impl_EchoApp_Echo_echoString_ 1
static void
impl_EchoApp_Echo_echoString(impl_POA_EchoApp_Echo *servant,
const CORBA_char * input,
CORBA_Environment *ev)
{
 /* ------   insert method code here   ------ */
 /* ------ ---------- end ------------ ------ */
}
#endif

