/* This is a template file generated by command */
/* orbit-idl-2 --skeleton-impl add-two-ints.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

#include "add-two-ints.h"

/*** App-specific servant structures ***/

#if !defined(_typedef_impl_POA_AddApp_Add_)
#define _typedef_impl_POA_AddApp_Add_ 1
typedef struct {
POA_AddApp_Add servant;
PortableServer_POA poa;
   /* ------ add private attributes here ------ */
   /* ------ ---------- end ------------ ------ */
} impl_POA_AddApp_Add;
#endif


/*** Implementation stub prototypes ***/

#if !defined(_decl_impl_AddApp_Add__destroy_)
#define _decl_impl_AddApp_Add__destroy_ 1
static void impl_AddApp_Add__destroy(impl_POA_AddApp_Add *servant,
CORBA_Environment *ev);
#endif

#if !defined(_decl_impl_AddApp_Add_addTwoInts_)
#define _decl_impl_AddApp_Add_addTwoInts_ 1
static void
impl_AddApp_Add_addTwoInts(impl_POA_AddApp_Add *servant,
const CORBA_short input_a,
const CORBA_short input_b,
CORBA_Environment *ev);
#endif


/*** epv structures ***/

#if !defined(_impl_AddApp_Add_base_epv_)
#define _impl_AddApp_Add_base_epv_ 1
static PortableServer_ServantBase__epv impl_AddApp_Add_base_epv = {
NULL,             /* _private data */
(gpointer) & impl_AddApp_Add__destroy, /* finalize routine */
NULL,             /* default_POA routine */
};
#endif

#if !defined(_impl_AddApp_Add_epv_)
#define _impl_AddApp_Add_epv_ 1
static POA_AddApp_Add__epv impl_AddApp_Add_epv = {
NULL, /* _private */
(gpointer)&impl_AddApp_Add_addTwoInts,
};
#endif


/*** vepv structures ***/

#if !defined(_impl_AddApp_Add_vepv_)
#define _impl_AddApp_Add_vepv_ 1
static POA_AddApp_Add__vepv impl_AddApp_Add_vepv = {
&impl_AddApp_Add_base_epv,
&impl_AddApp_Add_epv,
};
#endif


/*** Stub implementations ***/

#if !defined(_impl_AddApp_Add__create_)
#define _impl_AddApp_Add__create_ 1
static AddApp_Add impl_AddApp_Add__create(PortableServer_POA poa, CORBA_Environment *ev)
{
AddApp_Add retval;
impl_POA_AddApp_Add *newservant;
PortableServer_ObjectId *objid;

newservant = g_new0(impl_POA_AddApp_Add, 1);
newservant->servant.vepv = &impl_AddApp_Add_vepv;
newservant->poa = (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object)poa, ev);
POA_AddApp_Add__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

objid = PortableServer_POA_activate_object(poa, newservant, ev);
CORBA_free(objid);
retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

return retval;
}
#endif

#if !defined(_impl_AddApp_Add__destroy_)
#define _impl_AddApp_Add__destroy_ 1
static void
impl_AddApp_Add__destroy(impl_POA_AddApp_Add *servant, CORBA_Environment *ev)
{
    CORBA_Object_release ((CORBA_Object) servant->poa, ev);

    /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

POA_AddApp_Add__fini((PortableServer_Servant)servant, ev);

g_free (servant);
}
#endif

#if !defined(_impl_AddApp_Add_addTwoInts_)
#define _impl_AddApp_Add_addTwoInts_ 1
static void
impl_AddApp_Add_addTwoInts(impl_POA_AddApp_Add *servant,
const CORBA_short input_a,
const CORBA_short input_b,
CORBA_Environment *ev)
{
 /* ------   insert method code here   ------ */
 g_print(">> %d + %d = %d\n", input_a, input_b, input_a + input_b);
 /* ------ ---------- end ------------ ------ */
}
#endif

